# vim: set filetype=helm:
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mariadb-run-script.jobName" . }}
  labels:
    {{- include "mariadb-run-script.labels" . | nindent 4 }}
spec:  
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mariadb-run-script.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mariadb-run-script.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{- with .Values.runScript.inputFile }}
      - name: input
        persistentVolumeClaim:
          claimName: {{ .pvcName }}
      {{- end }}{{/* with .Values.runScript.inputFile */}}
      - name: home
        emptyDir: {}
      initContainers:
      - name: prepare-config
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        env:
        {{- with .Values.runScript.database }}
        - name: DB_HOST
          value: {{ .host }}
        - name: DB_PORT
          value: {{ .port | quote }}
        - name: DB_USER
          value: {{ .user }}
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .password.secretName }}
              key: {{ .password.key }}
        {{- end }}{{/* with .Values.runScript.database */}}
        command: [ "sh", "-ue" ]
        args:
        - -c
        - |-
          touch ~/.my.cnf && chmod -v u=rw,g=,o= ~/.my.cnf
          echo "[client]\nhost=${DB_HOST}\nport=${DB_PORT}\nuser=${DB_USER}\npassword=${DB_PASS}" > ~/.my.cnf
        volumeMounts:
        - name: home
          mountPath: /var/lib/mysql
      containers:
      - name: run-script
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        env:
        {{- with .Values.runScript.database }}
        - name: DB_NAME
          value: {{ .name }}
        {{- end }}{{/* with .Values.runScript.database */}}
        {{- if .Values.runScript.inputFile }}
        - name: INPUT_FILE
          value: {{ .Values.runScript.inputFile.filePath }}
        {{- else }}
        - name: INPUT_SQL
          value: {{ .Values.runScript.input.command | quote }}
        {{- end }}{{/* if .Values.runScript.inputFile */}}
        command:
        - sh
        - -xue
        - -c
        {{- if .Values.runScript.inputFile }}
        {{- if .Values.runScript.inputFile.gzipped }}
        - |-
          gzip -d -c ${INPUT_FILE} | mariadb -Bv --database=${DB_NAME}
        {{- else }} 
        - |-
          mariadb -Bv --database=${DB_NAME} < ${INPUT_FILE}
        {{- end }}{{/* if .Values.runScript.inputFile.gzipped */}}
        {{- else }}
        - |- 
          mariadb -Bv --database=${DB_NAME} --execute="${INPUT_SQL}" 
        {{- end }}{{/* if .Values.runScript.inputFile */}}
        workingDir: /work
        volumeMounts:
        - name: home
          mountPath: /var/lib/mysql
        {{- with .Values.runScript.inputFile }}
        - name: input
          mountPath: /work
          {{- with .subPath }}
          subPath: {{ . }}
          {{- end }}{{/* with .subPath */}}
          readOnly: true
        {{- end }}{{/* with .Values.runScript.inputFile */}}
        resources: {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
