image:
  repository: ghcr.io/eosc-lot-1/s3cmd
  pullPolicy: IfNotPresent
  tag: "2-alpine"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext: 
  capabilities:
    drop:
    - ALL
  #readOnlyRootFilesystem: true
  runAsNonRoot: true
  #runAsUser: 1000
  allowPrivilegeEscalation: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

pv:
  pvcName: data
  #subPath: xyz/123

s3:
  bucket: test
  #prefix: abc/789

s3cmd:
  debug: false
  config:
    secretName: s3cmd-config
  # command is one of: get, put
  command: get
  get:
    # S3 object under s3://BUCKET/PREFIX
    from: 1.txt
    # file under subPath of PV 
    to: 1.txt
  put:
    encrypt: false
    # file under subPath of PV 
    from:
    #from: 1.txt
    # S3 object under s3://BUCKET/PREFIX
    to:
    #to: 1.txt

