{{/* vim: set syntax=helm: */}}

{{- $fullname := include "thanos.fullname" . }}

{{- if .Values.store.netpol.enabled }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-store-allow-grpc-internal-1" $fullname }}
spec:
  podSelector:
    matchLabels:
      {{- include "thanos.selectorLabelsForStore" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    # allow from querier in same release
    - podSelector:
        matchLabels:
          {{- include "thanos.selectorLabelsForQuerier" . | nindent 10 }}
    ports:
    - port: grpc

{{- end }}{{/* if .Values.store.netpol.enabled */}}
