# vim: set syntax=helm:

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.serviceNameForStore" . }}
  labels:
    {{- include "thanos.labelsForStore" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: 10901
  - name: http
    port: 10908
    protocol: TCP
    targetPort: 10908
  selector:
    {{- include "thanos.selectorLabelsForStore" . | nindent 4 }}


