apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    app.kubernetes.io/name: matomo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: matomo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: matomo
    spec:
      containers:
        - name: matomo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: MATOMO_DATABASE_HOST
              value: {{ .Values.externalDatabase.host }}
            - name: MATOMO_DATABASE_PORT_NUMBER
              value: "{{ .Values.externalDatabase.port }}"
            - name: MATOMO_DATABASE_USER
              value: {{ .Values.externalDatabase.user }}
            - name: MATOMO_DATABASE_NAME
              value: {{ .Values.externalDatabase.database }}
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDatabase.passwordSecret }}
                  key: {{ .Values.externalDatabase.passwordSecretKey }}
          volumeMounts:
            - name: matomo-data
              mountPath: /var/www/html/config
      volumes:
        - name: matomo-data
          persistentVolumeClaim:
            claimName: {{ include "matomo.fullname" . }}

