apiVersion: v1
kind: Service
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    app.kubernetes.io/name: matomo
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "matomo.fullname" . }}
  ports:
    - name: http
      port: 8080
      targetPort: 80
    - name: https
      port: 8443
      targetPort: 443

