{{/* vim: set syntax=helm: */}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rsyslog.fullname" . }}
  labels:
    {{- include "rsyslog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 514
    protocol: TCP
    name: syslog
  selector:
    {{- include "rsyslog.selectorLabels" . | nindent 4 }}
