# vim: set filetype=helm:

{{- $timestamp := (now | date "20060102150405") }}

---
{{- if not (.Values.cronjob.enabled) }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s" (include "mariadb-backup.fullname" .) $timestamp }}
  labels:
    {{- include "mariadb-backup.labels" . | nindent 4 }}
spec:  
  {{- include "mariadb-backup.jobSpec" . | nindent 2 }}

{{- end }}{{/* not (.Values.cronjob.enabled) */}}
