# vim: set filetype=helm:

{{- $timestamp := (now | date "20060102150405") }}
{{- $jobName := printf "%s-%s" (include "mariadb-backup.fullname" .) $timestamp }}
{{- $outputName := .Values.backup.outputFile.fileName | default (printf "%s@%s.sql.gz" .Values.backup.database.name $timestamp) }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  labels:
    {{- include "mariadb-backup.labels" . | nindent 4 }}
spec:  
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mariadb-backup.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mariadb-backup.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: output
        persistentVolumeClaim:
          claimName: {{ .Values.backup.outputFile.pvcName }}
      - name: mariadb-home
        emptyDir: {}  
      - name: temp
        emptyDir: {}
      {{- if .Values.backup.s3.bucket }}
      - name: s3cmd-config
        secret:
          secretName: {{ .Values.s3cmd.config.secretName }}
          defaultMode: 0640
      - name: gnupg-home
        emptyDir: {}
      {{- end }}
      initContainers:
      - name: prepare-config
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        env:
        {{- with .Values.backup.database }}
        - name: DB_HOST
          value: {{ .host }}
        - name: DB_PORT
          value: {{ .port | quote }}
        - name: DB_USER
          value: {{ .user }}
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .password.secretName }}
              key: {{ .password.key }}
        {{- end }}{{/* with .Values.backup.database */}}
        command: [ "sh", "-ue" ]
        args:
        - -c
        - |-
          touch ~/.my.cnf && chmod -v u=rw,g=,o= ~/.my.cnf
          echo "[client]\nhost=${DB_HOST}\nport=${DB_PORT}\nuser=${DB_USER}\npassword=${DB_PASS}" > ~/.my.cnf
        volumeMounts:
        - name: mariadb-home
          mountPath: /var/lib/mysql
      - name: backup
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        env:
        - name: DB_NAME
          value: {{ .Values.backup.database.name }}
        - name: OUTPUT_NAME
          value: {{ $outputName }}
        command:
        - sh
        - -xue
        - -c
        - |-
          mariadb-dump --lock-tables -v ${DB_NAME} | gzip -c > "${OUTPUT_NAME}"
        workingDir: /work
        volumeMounts:
        - name: mariadb-home
          mountPath: /var/lib/mysql
        {{- with .Values.backup.outputFile }}
        - name: output
          mountPath: /work
          {{- with .subPath }}
          subPath: {{ . }}
          {{- end }}{{/* with .subPath */}}
        {{- end }}{{/* with .Values.backup.outputFile */}}
        resources: {{- toYaml .Values.resources | nindent 10 }} 
      {{- if .Values.backup.s3.bucket }}
      - name: s3cmd
        image: "{{ .Values.s3cmd.image.repository }}:{{ .Values.s3cmd.image.tag }}"
        imagePullPolicy: {{ .Values.s3cmd.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        env:
        - name: OUTPUT_NAME
          value: {{ $outputName }}
        - name: DEST_URL
          value: {{ printf "s3://%s/%s/%s" (.Values.backup.s3.bucket) (.Values.backup.s3.prefix | default "") $outputName }}
        command:
        - s3cmd
        {{- if .Values.s3cmd.debug }}
        - --debug
        {{- else }}
        - --verbose
        {{- end }}{{/* if .Values.s3cmd.debug */}}
        {{- if .Values.backup.s3.encrypt }}
        - --encrypt
        {{- end }}{{/* if .Values.backup.s3.encrypt */}}
        - --no-preserve
        - put
        - $(OUTPUT_NAME)
        - $(DEST_URL)
        workingDir: /work
        volumeMounts:
        - name: s3cmd-config
          mountPath: /.s3cfg
          subPath: s3cmd.conf
          readOnly: true
        - name: gnupg-home
          mountPath: /.gnupg
        - name: temp
          mountPath: /tmp
        {{- with .Values.backup.outputFile }}
        - name: output
          mountPath: /work
          {{- with .subPath }}
          subPath: {{ . }}
          {{- end }}{{/* with .subPath */}}
        {{- end }}{{/* with .Values.backup.outputFile */}}
        resources: {{- toYaml .Values.resources | nindent 10 }} 
      {{- end }}{{/* if .Values.backup.s3.bucket */}}
      containers:
      - name: stat
        image: busybox:1.36
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        env:
        - name: OUTPUT_NAME
          value: {{ $outputName }}
        command:
        - stat
        - $(OUTPUT_NAME)
        workingDir: /work
        volumeMounts:
        {{- with .Values.backup.outputFile }}
        - name: output
          mountPath: /work
          {{- with .subPath }}
          subPath: {{ . }}
          {{- end }}{{/* with .subPath */}}
        {{- end }}{{/* with .Values.backup.outputFile */}}
        resources: {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
