imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  allowPrivilegeEscalation: false

resources: 
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

githubRepo:
  name: NowhereLand/helloworld
  tag: main
  # a personal access token with read permissions on the repo
  accessToken: 
    secretName: github-access-token
    key: token

job:
  # path to file (relative to github repo)
  filePath: path/to/1.xt 
  outputFilePath: out/1.txt
  #persistence:
  #  pvcName:
  #  subPath:
  download:
    image:
      repository: ghcr.io/eosc-lot-1/curl-jq
      pullPolicy: IfNotPresent
      tag: "8"
  process:
    image:
      repository: alpine
      pullPolicy: IfNotPresent
      tag: "3.19"
    extraEnv: []
    #- name: foo
    #  value: Bar  
    command: 
    - sh
    - -c
    - >-
      stat ${outputFilePath}
  
