# vim: set syntax=helm:

{{- $fullname := (include "rabbitmq.fullname" .) }}

# manifests
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullname }} 
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "rabbitmq.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullname }}

