# vim: set syntax=helm:

{{- $adminPasswordSecret := lookup "v1" "Secret" .Release.Namespace (include "rabbitmq.adminPassword.secretName" .) }}

# manifests
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-curlrc-admin" (include "rabbitmq.fullname" .) }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
stringData:
  curlrc: |+
    user="admin:{{ $adminPasswordSecret | dig "data" "password" "" | b64dec }}"
