replicaCount: 1

image:
  repository: matomo
  tag: 5.1.2-apache
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

externalDatabase:
  host: matomo-mariadb
  port: 3306
  user: matomo
  database: matomo
  passwordSecret: matomo-mariadb-password
  passwordSecretKey: db-password

podSecurityContext:
  enabled: true
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault

persistence:
  existingClaim: matomo-data

resources:
  limits:
    memory: 1024Mi
    cpu: 750m
  requests:
    memory: 256Mi
    cpu: 250m
