name: CI - s3cmd
run-name: Build container image with s3cmd

on: 
  push:
    #paths:
    #- 'gnupg/**'
    #- '.github/workflows/docker-build-s3cmd.yml'
    branches:
    - 's3cmd'
    tags:
    - '0.*'
    - '1.*'

permissions:
  actions: read
  checks: read
  contents: read
  packages: write
  repository-projects: read
  statuses: read

jobs:

  build_image:
    runs-on: ubuntu-22.04
    env:
      {}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: |
          ghcr.io/eosc-lot-1/s3cmd
    - uses: docker/setup-buildx-action@v3
      with:
        driver: docker
    - uses: docker/build-push-action@v5
      with:
        context: ./s3cmd/docker/
        file: ./s3cmd/docker/Dockerfile
        #buildArgs: |-
        push: true
        tags: |
          ghcr.io/eosc-lot-1/s3cmd:2-alpine
        labels: ${{ steps.meta.outputs.labels }}

