name: CI - curl-jq
run-name: Build container image for curl-jq

on: 
  push:
    paths:
    - 'curl/**'
    - '.github/workflows/docker-build-curl-jq.yml'
    branches:
    - 'curl-jq'
    tags:
    - '0.*'
    - '1.*'

jobs:

  build_image:
    runs-on: ubuntu-22.04
    env:
      {}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: |
          ghcr.io/eosc-lot-1/curl-jq
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: ./curl-jq/docker/
        file: ./curl-jq/docker/Dockerfile
        #buildArgs: |-
        push: true
        tags: |
          ghcr.io/eosc-lot-1/curl-jq:8
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

