name: CI - ssmtp
run-name: Build container image for msmtp

on: 
  push:
    branches:
    - 'msmtp'
    tags:
    - '0.*'
    - '1.*'

permissions:
  actions: read
  checks: read
  contents: read
  packages: write
  repository-projects: read
  statuses: read

jobs:

  build_image:
    runs-on: ubuntu-22.04
    env:
      {}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: |
          ghcr.io/eosc-lot-1/msmtp
    - uses: docker/setup-buildx-action@v3
      with:
        driver: docker
    - uses: docker/build-push-action@v5
      with:
        context: ./msmtp/docker/
        file: ./msmtp/docker/Dockerfile
        #buildArgs: |-
        push: true
        tags: |
          ghcr.io/eosc-lot-1/msmtp:1
        labels: ${{ steps.meta.outputs.labels }}

