name: CI - rsyslog
run-name: Build container image for rsyslog/logrotate

on: 
  push:
    #paths:
    #- 'rsyslog/**'
    #- '.github/workflows/docker-build-rsyslog.yml'
    branches:
    - 'rsyslog'
    tags:
    - '0.*'
    - '1.*'

permissions:
  actions: read
  checks: read
  contents: read
  packages: write
  repository-projects: read
  statuses: read

jobs:

  build_image:
    runs-on: ubuntu-22.04
    env:
      {}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
      with:
        driver: docker
    - uses: docker/bake-action@v5
      with:
        workdir: ./rsyslog
        targets: >-
          rsyslog,logrotate
        push: true
        set: |
          rsyslog.tags=ghcr.io/eosc-lot-1/rsyslog:8-alpine
          logrotate.tags=ghcr.io/eosc-lot-1/logrotate:3-alpine
 
