name: CI - pgpool
run-name: Build container image for PgPool


on: 
  push:
    #paths:
    #- 'postgresql-cluster'
    branches:
    - 'pgpool'
    tags:
    - '0.*'
    - '1.*'

permissions:
  actions: read
  checks: read
  contents: read
  packages: write
  repository-projects: read
  statuses: read

jobs:

  build_image:
    runs-on: ubuntu-22.04
    env:
      pgpool_version: "4.4"
    steps:
    - uses: actions/checkout@v3
    - run: |-
        git submodule init postgresql-cluster
        git submodule update postgresql-cluster
    - run: ls -hal postgresql-cluster
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: |
          ghcr.io/eosc-lot-1/pgpool
    - uses: docker/setup-buildx-action@v3
      with:
        driver: docker
    - uses: docker/build-push-action@v5
      with:
        context: ./postgresql-cluster/pgpool/redhat/
        file: postgresql-cluster/pgpool/redhat/Dockerfile
        #buildArgs: |-
        push: true
        tags: |
          ghcr.io/eosc-lot-1/pgpool:${{ env.pgpool_version }}-redhat
        labels: ${{ steps.meta.outputs.labels }}

